{
    'name': 'User Activity Logs',
    'version': '18.0',
    'category': 'Extra Tools',
    'summary': 'Track user activities and actions in the system.',
    'description': 'This module logs user actions, including create, update, delete events.',
    'author': 'GRAAHO TECHNOLOGIES LLC',
    'company': 'Graaho Technologies LLC',
    'maintainer': 'GRAAHO TECHNOLOGIES LLC',
    'website': 'https://www.graaho.com',
    'depends': ['base', 'purchase', 'stock', 'product', 'account'],
    'license': 'LGPL-3',
    'data': [
        'security/user_activity_log_security.xml',
        'security/ir.model.access.csv',
        'views/user_activity_views.xml',
    ],
    'images': ['static/description/banner.jpg'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'price': '2.99',
    'currency': 'USD',
}
